#!/bin/bash
names_file="/home/roflcoffel/Programming/Bash/HoloSelect/names"
youtube="https://www.youtube.com/@"

declare -A all_members=(
	[Gura]="GawrGura"
	[Calli]="MoriCalliope"
	[Ame]="WatsonAmelia"
	[Kiara]="TakanashiKiara"
	[Ina]="NinomaeInanis"
	[Reine]="PavoliaReine"
	[Iofi]="AraniIofifteen"
	[Ollie]="KureijiOllie"
	[Moona]="MoonaHoshinova"
	[Anya]="AnyaMelfissa"
	[Risu]="AyundaRisu"
	[Towa]="TokoyamiTowa"
	[Nene]="MomosuzuNene"
	[Marine]="HoushouMarine"
	[Botan]="ShishiroBotan"
	[Korone]="InugamiKorone"
	[Suisei]="HoshimachiSuisei"
	[Roboco]="RobocoSan"
	[Okayu]="NekomataOkayu"
	[Hachama]="AkaiHaato"
	[Ayame]="NakiriAyame"
	[Choco]="YuzukiChoco"
	[Luna]="HimemoriLuna"
	[Lamy]="YukihanaLamy"
	[Aqua]="MinatoAqua"
	[Matsuri]="NatsuiroMatsuri"
	[Sora]="TokinoSora"
	[Shion]="MurasakiShion"
	[Kanata]="AmaneKanata"
	[Watame]="TsunomakiWatame"
	[Polka]="OmaruPolka"
	[Subaru]="OozoraSubaru"
	[Aki]="AkiRosenthal"
	[Miko]="SakuraMiko"
	[Noel]="ShiroganeNoel"
	[Flare]="ShiranuiFlare"
	[Mio]="OokamiMio"
	[Fubuki]="ShirakamiFubuki"
	[Pekora]="UsadaPekora"
	[AZKI]="AZKI"
	[IRyS]="IRyS"
	[Kaela]="KaelaKovalskia"
	[Zeta]="VestiaZeta"
	[Kobo]="KoboKanaeru"
	[Fauna]="CeresFauna"
	[Kronii]="OuroKronii"
	[Mumei]="NanashiMumei"
	[Bae]="HakosBaelz"
	[Bijou]="KosekiBijou"
	[Shiori]="ShioriNovella"
	[Nerissa]="NerissaRavencraft"
	[Fuwamoco]="FUWAMOCOch"
	[Ao]="HiodoshiAo"
	[Hajime]="TodorokiHajime"
	[Ririka]="IchijouRirika"
	[Raden]="JuufuuteiRaden"
	[Kanade]="OtonoseKanade"
)

member="$(cat $names_file | dmenu -i)"

vivaldi-stable "$youtube${all_members[$member]}"
